#pragma once

#include "botutil/base_sched.h"
#include "botutil/base_task.h"

#include "botutil/tf2/attack_point_sched.h"
#include "botutil/tf2/attack_point_task.h"
#include "botutil/tf2/attack_sentrygun_sched.h"
#include "botutil/tf2/attack_sentrygun_task.h"
#include "botutil/tf2/cover_interrupt.h"
#include "botutil/tf2/defend_payload_bomb_sched.h"
#include "botutil/tf2/defend_payload_bomb_task.h"
#include "botutil/tf2/defend_point_sched.h"
#include "botutil/tf2/defend_point_task.h"
#include "botutil/tf2/get_ammo_sched.h"
#include "botutil/tf2/get_flag_sched.h"
#include "botutil/tf2/get_health_sched.h"
#include "botutil/tf2/hurt_interrupt.h"
#include "botutil/tf2/mess_around_sched.h"
#include "botutil/tf2/nest_task.h"
#include "botutil/tf2/push_payload_bomb_sched.h"
#include "botutil/tf2/push_payload_bomb_task.h"
#include "botutil/tf2/shoot_last_enemy_position_sched.h"
#include "botutil/tf2/shoot_last_enemy_position_task.h"
#include "botutil/tf2/spam_task.h"
#include "botutil/tf2/spy_check_task.h"
#include "botutil/tf2/taunt_sched.h"
#include "botutil/tf2/taunt_task.h"
#include "botutil/tf2/use_dispenser_sched.h"
#include "botutil/tf2/use_teleporter_sched.h"
#include "botutil/tf2/use_teleporter_task.h"
#include "botutil/tf2/voice_command_task.h"
#include "botutil/tf2/wait_ammo_task.h"
#include "botutil/tf2/wait_flag_sched.h"
#include "botutil/tf2/wait_flag_task.h"
#include "botutil/tf2/wait_health_task.h"

#include "botutil/tf2/demo/find_pipe_waypoint_task.h"
#include "botutil/tf2/demo/pipe_enemy_sched.h"
#include "botutil/tf2/demo/pipe_enemy_task.h"
#include "botutil/tf2/demo/pipejump_task.h"
#include "botutil/tf2/demo/pipetrap_sched.h"
#include "botutil/tf2/demo/pipetrap_task.h"

#include "botutil/tf2/engi/build_building_sched.h"
#include "botutil/tf2/engi/build_building_task.h"
#include "botutil/tf2/engi/get_metal_sched.h"
#include "botutil/tf2/engi/interrupt.h"
#include "botutil/tf2/engi/look_after_sentry_sched.h"
#include "botutil/tf2/engi/look_after_task.h"
#include "botutil/tf2/engi/move_building_sched.h"
#include "botutil/tf2/engi/pickup_building_task.h"
#include "botutil/tf2/engi/place_building_task.h"
#include "botutil/tf2/engi/remove_sapper_sched.h"
#include "botutil/tf2/engi/remove_sapper_task.h"
#include "botutil/tf2/engi/upgrade_building_sched.h"
#include "botutil/tf2/engi/upgrade_building_task.h"

#include "botutil/tf2/medic/heal_sched.h"
#include "botutil/tf2/medic/heal_task.h"

#include "botutil/tf2/scout/double_jump_task.h"
#include "botutil/tf2/scout/use_lunchbox_drink_task.h"

#include "botutil/tf2/sniper/snipe_crossbow_sched.h"
#include "botutil/tf2/sniper/snipe_crossbow_task.h"
#include "botutil/tf2/sniper/snipe_sched.h"
#include "botutil/tf2/sniper/snipe_task.h"

#include "botutil/tf2/soldier/rocket_jump_task.h"
#include "botutil/tf2/soldier/use_buff_item_task.h"

#include "botutil/tf2/spy/backstab_task.h"
#include "botutil/tf2/spy/backstap_sched.h"
#include "botutil/tf2/spy/disguise_task.h"
#include "botutil/tf2/spy/sap_sched.h"
#include "botutil/tf2/spy/sap_task.h"